language: c

compiler:
  - gcc

before_install:
  - sudo apt-get update
  # Install dependencies required for configuration
  - sudo apt-get install autoconf libtool pkg-config 
  # Upgrade gcc
  - gcc --version
  # Install dependencies
  - sudo apt-get install libatlas-base-dev libfftw3-dev libshp-dev libplplot-dev
  
install :
  - sh autogen.sh
  
script :
  - ./configure
  - make
  
os : 
  - linux
